name: blackcoffer_test
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.5
  numeral: ^2.0.1
  firebase_core: ^2.24.2
  firebase_auth: ^4.6.0
  cloud_firestore: ^4.7.0
  timeago: ^3.4.0
  intl: ^0.18.1
  image_picker: ^0.8.7+5
  image_cropper: ^3.0.3
  fluttertoast: ^8.2.1
  firebase_storage: ^11.2.0
  flutter_image_slider: ^0.0.2
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  map_launcher: ^2.5.0+1
  uuid: ^3.0.7
  provider: ^6.0.5
  google_maps_flutter: ^2.5.3
  shake: ^2.2.0
  flutter_launcher_icons: ^0.13.1
  get: ^4.6.5
  pinput: ^3.0.1
  camera: ^0.10.5+5
  video_player: ^2.7.0
  path_provider: ^2.1.1
  simple_circular_progress_bar: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/blackcoffer.png
    - assets/explore.png
    - assets/explore_active.png
    - assets/library.png
    - assets/library_active.png
    - assets/new.jpg
    - assets/dp.jpg
    - assets/video.mp4
