// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVPsmucU5Ja3vKaddsqSSZ7yhMBKLqhOc',
    appId: '1:171459677318:web:d97e630b26411b54e11507',
    messagingSenderId: '171459677318',
    projectId: 'blackcoffer-test-9f149',
    authDomain: 'blackcoffer-test-9f149.firebaseapp.com',
    storageBucket: 'blackcoffer-test-9f149.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRvZjopaPcqKOFPryD4aJNWmrTfqR7QiY',
    appId: '1:171459677318:android:20cd47c9730f6d7ee11507',
    messagingSenderId: '171459677318',
    projectId: 'blackcoffer-test-9f149',
    storageBucket: 'blackcoffer-test-9f149.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAlpu981BihOSAClHPY6qZB-IgTGB97M0',
    appId: '1:171459677318:ios:3728f5a4b7cbcc6fe11507',
    messagingSenderId: '171459677318',
    projectId: 'blackcoffer-test-9f149',
    storageBucket: 'blackcoffer-test-9f149.appspot.com',
    iosBundleId: 'com.example.blackcofferTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAlpu981BihOSAClHPY6qZB-IgTGB97M0',
    appId: '1:171459677318:ios:3728f5a4b7cbcc6fe11507',
    messagingSenderId: '171459677318',
    projectId: 'blackcoffer-test-9f149',
    storageBucket: 'blackcoffer-test-9f149.appspot.com',
    iosBundleId: 'com.example.blackcofferTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVPsmucU5Ja3vKaddsqSSZ7yhMBKLqhOc',
    appId: '1:171459677318:web:a23e09e59c9e62d8e11507',
    messagingSenderId: '171459677318',
    projectId: 'blackcoffer-test-9f149',
    authDomain: 'blackcoffer-test-9f149.firebaseapp.com',
    storageBucket: 'blackcoffer-test-9f149.appspot.com',
  );
}
