// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbffD-sR06rWqSufW8FsBJbExoXeJ2qg8',
    appId: '1:642315707176:web:6c776598b10e1fbdaf661d',
    messagingSenderId: '642315707176',
    projectId: 'blackcoffer-test-bcc7e',
    authDomain: 'blackcoffer-test-bcc7e.firebaseapp.com',
    storageBucket: 'blackcoffer-test-bcc7e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdqngtjJWin9lWXlvkiMoTh9rS46ZQl3A',
    appId: '1:642315707176:android:92eeaa57acc602eaaf661d',
    messagingSenderId: '642315707176',
    projectId: 'blackcoffer-test-bcc7e',
    storageBucket: 'blackcoffer-test-bcc7e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpYMNV3Kt8IrhUs-G0mqaZkg8FHfgCqh0',
    appId: '1:642315707176:ios:2c47589768348781af661d',
    messagingSenderId: '642315707176',
    projectId: 'blackcoffer-test-bcc7e',
    storageBucket: 'blackcoffer-test-bcc7e.appspot.com',
    iosBundleId: 'com.example.blackcofferTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpYMNV3Kt8IrhUs-G0mqaZkg8FHfgCqh0',
    appId: '1:642315707176:ios:2c47589768348781af661d',
    messagingSenderId: '642315707176',
    projectId: 'blackcoffer-test-bcc7e',
    storageBucket: 'blackcoffer-test-bcc7e.appspot.com',
    iosBundleId: 'com.example.blackcofferTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbffD-sR06rWqSufW8FsBJbExoXeJ2qg8',
    appId: '1:642315707176:web:f0a64675f12f0c9eaf661d',
    messagingSenderId: '642315707176',
    projectId: 'blackcoffer-test-bcc7e',
    authDomain: 'blackcoffer-test-bcc7e.firebaseapp.com',
    storageBucket: 'blackcoffer-test-bcc7e.appspot.com',
  );
}
